name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: 0 0 * * 0

jobs:
  build:
    strategy:
      matrix:
        libc:
          - glibc
          - musl
          - uclibc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: ./build.sh ${{ matrix.libc }}
